### PR TITLE
fix: use egl instead of sfml-window to create opengl context

### PR DESCRIPTION
**Pull request by deadbeef84**
There's a bug in sfml-window/x11 that causes opengl initialization to crash. sfml-window also uses GLX, and it's my understanding that EGL offers closer access to hardware (e.g zero-copy GPU buffer sharing via DMABUF) so I think this is the way to go on linux. It also removes the indirect x11 dependency in sfml-window/gl-context (html/cef, screen and diag modules still depends on x11).

### CODE REVIEW

**Review by ronag — APPROVED** [review]
Good job!

**Comment by ronag** [comment]
Some conflicts though

**Comment by deadbeef84** [comment]
Fixed conflicts

**Comment by ronag** [comment]
LGTM: feel free to merge

**Pull request merged**
