### PR TITLE
FFMPEG Producer Rewrite WIP

### PR DESCRIPTION
**Pull request by ronag**
- FFMMPEG 3.4.1
- Replace custom implementations with FFMPEG filters and utils
- Fixed timestamp handling
- Fixed V/A sync
- Fixed looping
- Fixed seeking
- Fixed duration
- Improved stability
- Improved performance
- Audio resampling to match timestamps
- Fixed invalid interlaced YUV (411, 420) handling
- Added YUVA444, YUVA422 support
- Added IO timeout
- Added HTTP reconnect
- Significantly improved auto conversion (fps, field mode, scaling etc..). Should play "anything"
- FFMPEG video filter support
- FFMPEG audio filter support
- CALL SEEK returns actually seeked value (useful during relative seeking)
- All AMCP timings (seek, duration, in, out etc...) is based on the channel format
- Removed "frame-number" and "nb-frames" from INFO response. They make no sense. Use "file-" versions instead
- Misc minor fixes, improvements, and cleanup

# TODO 1
- [x] INFO  
- [x] OSC
- [x] LOOP
- [x] CALL SEEK (latest wins, update current frame)
- [x] Auto merge multiple audio tracks (e.g. some mxf)
- [x] Secondary video stream is alpha
- [ ] Linux Build

# TODO 2

- [ ] option for default filter override
- [ ] CALL VFILTER
- [ ] CALL AFILTER

# TODO 3

- [ ] ts discontinuity
- [ ] variable framerate input
- [ ] timeout & retry
- [ ] further improvements to duration (use actual duration when looping)
- [ ] edge cases when input start_time is not set?
- [ ] What if audio & video pts from input is out of sync / discontinious?
- [x] Use separate threads for audio decoding, video decoding, audio filter, video filter
- [x] pixel_constraints(). What is this?
- [ ] Move more stuff to GPU (nice to have)
- [ ] vid_params

# TODO 4

- [ ] custom_channel_order
- [ ] FRAMERATE
- [ ] thread priorities
  
# Binaries

# Notes

Only debug build will currently compile.

### CODE REVIEW

**Comment by dimitry-ishenko** [comment]
@ronag did you update linux deps as well? or is it windows only for now?

**Comment by ronag** [comment]
Only windows debug for now

**Comment by dimitry-ishenko** [comment]
OK

**Comment by mint-dewit** [comment]
Are you compiling FFMPEG with NDI support?

**Comment by premultiply** [comment]
Small thing to improve: Replace old **yadif** with improved **bwdif** deinterlacer.
You just need to replace the word yadif with bwdif in casparcg code files. Everything else keeps the same.

**Comment by ronag** [comment]
Just took the latest build from ffmpeg.org.

I’m not big on building ffmpeg on windows.

**Comment by mint-dewit** [comment]
@premultiply is that something we should do in the decklink producer as well, perhaps?

@ronag I've been struggling to get the library files for 3.4.1 compiled on linux, so I feel you.

**Comment by premultiply** [comment]
@baltedewit Yes. And anywhere else where yadif is currently in use.

**Comment by ronag** [comment]
@premultiply how's the performance between yadif vs bwdif?

I'm going on vacation next week so progress here is going to be paused a little.

**Comment by dimitry-ishenko** [comment]
@ronag not sure if you saw my comment at the top. I think you have a typo in the `call` function for the `length` parameter

**Comment by ronag** [comment]
@dimitry-ishenko: yes I saw it... no worries :)

I won't push anything new since I can't test on my laptop. Will do when I'm back at the office after next week.

**Comment by premultiply** [comment]
@ronag There should not be much difference in performance but in visual quality.

**Review by premultiply — COMMENTED** [review]
I think there is no need to do extra idet filtering. The deinterlacer does this on his own and skips/passes progressive input frames.

**Comment by ronag** [comment]
@premultiply: Yes, the problem is that frames are not always correctly tagged as interlaced or not-interlaced, e.g. video from bloomberg are often interlaced but not properly identified by ffmpeg as interlaced. The idet filter can auto fix this. Not sure if this is maybe a bit too much magic or not...

**Comment by mint-dewit** [comment]
Proposal for a todo: linux dependencies.

**Comment by ronag** [comment]
closed in favor of https://github.com/CasparCG/Server/pull/679

**Pull request closed without merging**
